[package]
name = "ccsds"
version = "0.1.0-alpha.5"
authors = ["Bruce Flynn <brucef@ssec.wisc.edu>"]
edition = "2021"
description = "CCSDS spacecraft data stream decoding"
keywords = ["ccsds", "spacepacket", "framing", "cadu"]
categories = ["aerospace::space-protocols"]
license-file = "LICENSE.txt"
repository = "https://github.com/bmflynn/ccsds-rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = { version = "0.4", features = ["serde"] }
crossbeam = { version = "0.8.4", features = ["crossbeam-channel"] }
ndarray = "0.15.6"
rayon = "1.7.0"
rs2 = "0.1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "1.0.38"
threadpool = "1.8.1"

[lib]
name = "ccsds"
path = "src/lib.rs"

[dev-dependencies]
hex = "0.4.3"
md-5 = "0.10.6"
rand = "0.8.5"
tempfile = "3.9.0"
