[package]
name = "ccsds"
version = "0.1.0-alpha.0"
authors = ["Bruce Flynn <brucef@ssec.wisc.edu>"]
edition = "2021"
repository = "https://github.com/bmflynn/ccsds"
description = "CCSDS spacecraft data stream decoding"
keywords = ["ccsds"]
categories = ["aerospace::space-protocols"]
license_file = "LICENSE.txt"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = { version = "0.4", features = ["serde"] }
ndarray = "0.15.6"
rayon = "1.7.0"
rs2 = "0.1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "1.0.38"
threadpool = "1.8.1"

[lib]
name = "ccsds"
path = "src/lib.rs"

[dev-dependencies]
rand = "0.8.5"
