[package]
name = "ccsds"
version = "0.1.0"
authors = ["Bruce Flynn <brucef@ssec.wisc.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4"
clap = { version = "4.0.29", features = ["derive"] }

[lib]
name = "ccsds"
path = "src/lib.rs"

[[bin]]
name = "spacepackets"
path = "src/bin/spacepackets/bin.rs"
