name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        lfs: true
    - name: Git LFS Pull
      run: |
        git lfs pull
    - name: Git LFS Checkout 
      run: |
        git lfs checkout 
    - name: List test files 
      run: |
        find lib/tests 
    - name: Build
      run: cargo build
    - name: Run tests
      run: cargo test
